apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: configtest
    spec:
      containers:
      - name: envtest
        image: kubernetes_demo_config_map
        ports:
        - containerPort: 3000


